import {
  useEffect,
  useMemo,
  useState,
} from 'react'

import {
  Link,
  NavLink,
  useLocation,
} from 'react-router-dom'

import {
  Boxes,
  ChevronDown,
  ChevronRight,
  Circle,
  FlaskConical,
  Gamepad2,
  LayoutDashboard,
  LoaderCircle,
  Users,
  Wrench,
} from 'lucide-react'
import {
  getRepairCases,
} from '../api/repairCaseApi'


// repair case statuses that can be displayed
const REPAIR_STATUSES = [
  'OPEN',
  'IN_PROGRESS',
  'CLOSED',
]


// main sidebar component, isOpen received from parent component
const Sidebar = ({ isOpen }) => {

  // info about current Router location, pathname used to reload repair cases when the current route changes
  const location = useLocation()

  // control whether the general repair case menu is expanded
  const [
    repairCasesOpen,
    setRepairCasesOpen,
  ] = useState(false)
  // store currently expanded repair case status, null for no status group being expanded
  const [
    openStatus,
    setOpenStatus,
  ] = useState(null)

  // store repair cases retrieved from backend
  const [
    repairCases,
    setRepairCases,
  ] = useState([])
  const [
    loadingRepairCases,
    setLoadingRepairCases,
  ] = useState(true)
  // error message if repair case request fails
  const [
    repairCasesError,
    setRepairCasesError,
  ] = useState('')


  // load real repair cases from backend when sidebar is mounted or pathname changes
  useEffect(() => {
    let componentMounted = true
    const loadRepairCases = async () => {
      try {
        setLoadingRepairCases(true)
        setRepairCasesError('')
        const data =
          await getRepairCases()
        if (!componentMounted) {
          return
        }


        // store response, Array.isArray makes sure that repair cases always contains an array
        setRepairCases(
          Array.isArray(data)
            ? data
            : [],
        )

      } catch (requestError) {
        if (!componentMounted) {
          return
        }


        // try to display error message generated by backend
        setRepairCasesError(
          requestError.response
            ?.data
            ?.message ??
            'Could not load repair cases.',
        )
      } finally {
        if (componentMounted) {
          setLoadingRepairCases(false)
        }
      }
    }


    // function executed when the custom event is dispatched
    const handleRepairCasesChanged =
      () => {loadRepairCases()
      }
    loadRepairCases()
    window.addEventListener(
      'retrolab:repair-cases-changed',
      handleRepairCasesChanged,
    )


    // cleanup
    return () => {
      componentMounted = false
      window.removeEventListener(
        'retrolab:repair-cases-changed',
        handleRepairCasesChanged,
      )
    }
  }, [location.pathname])


  // group repair cases according to status

  const repairCasesByStatus =
    useMemo(() => {

      return REPAIR_STATUSES
        .map((status) => ({
          status,
          // select only the ones corresponding to that status
          cases: repairCases.filter(
            (repairCase) =>
              repairCase.status ===
              status,
          ),
        }))
        // remove groups that have no repair cases
        .filter(
          (statusGroup) =>
            statusGroup.cases.length >
            0,
        )
    }, [repairCases])


  // open or close repair case status groups, if open set to null and close
  const toggleStatus = (status) => {
    setOpenStatus(
      (currentStatus) =>
        currentStatus === status
          ? null
          : status,
    )
  }


  // shared Tailwind style for Navlink
  const navLinkStyle = ({
    isActive,
  }) =>
    `flex w-full items-center gap-3 rounded-lg px-3 py-3 text-white transition-colors ${
      isActive
        ? 'bg-slate-800'
        : 'hover:bg-slate-800'
    }`
  // shared style for normal menu buttons
  const menuButtonStyle =
    'flex w-full items-center gap-3 rounded-lg px-3 py-3 text-white transition-colors hover:bg-slate-800'
  // main nav icons style
  const iconStyle =
    'h-5 w-5 shrink-0'
  return (
    <aside

      // sidebar fixed to the left, isOpen controls horizontal position
      className={`fixed left-0 top-0 z-20 flex h-screen w-64 flex-col bg-slate-900 px-4 py-6 transition-transform duration-300 ${
        isOpen
          ? 'translate-x-0'
          : '-translate-x-full'
      }`}
    >
      <Link
        to="/"
        className="mb-10 block overflow-hidden"
      >
        <h1 className="w-4/5 whitespace-nowrap font-logo font-bold text-[45px] leading-none px-2.5 text-white">
          RetroLab
        </h1>
      </Link>
      <nav className="flex min-h-0 flex-1 flex-col">

        <div className="flex-1 overflow-y-auto pr-1">

          <ul className="space-y-2">
            <li>
              <NavLink
                to="/"

                /*
                 * end prevents "/" from being considered active for every route beginning with /
                 */
                end

                className={navLinkStyle}
              >
                <LayoutDashboard
                  className={iconStyle}
                />

                <span>
                  Dashboard
                </span>
              </NavLink>
            </li>
            <li>
              <NavLink
                to="/consoles"
                className={navLinkStyle}
              >
                <Gamepad2
                  className={iconStyle}
                />

                <span>
                  Consoles
                </span>
              </NavLink>
            </li>
            <li>
              <button
                type="button"

                /*
                 * toggle the Repair Cases submenu
                 */
                onClick={() =>
                  setRepairCasesOpen(
                    (currentValue) =>
                      !currentValue,
                  )
                }

                className={
                  menuButtonStyle
                }

                aria-expanded={
                  repairCasesOpen
                }
              >
                <Wrench
                  className={iconStyle}
                />

                <span className="flex-1 text-left">
                  Repair Cases
                </span>


                {/*
                 * change arrow
                 */}
                {repairCasesOpen ? (
                  <ChevronDown className="h-4 w-4 shrink-0" />
                ) : (
                  <ChevronRight className="h-4 w-4 shrink-0" />
                )}

              </button>


              {/*
               *render submenu only when open
               */}
              {repairCasesOpen && (

                <div className="ml-5 mt-2 border-l border-slate-700 pl-3">


                  {/*
                   *conditional rendering
                   */}
                  {loadingRepairCases ? (

                    <div className="flex items-center gap-2 px-2 py-3 text-xs text-slate-400">
                      <LoaderCircle className="h-4 w-4 animate-spin" />
                      <span>
                        Loading cases...
                      </span>
                    </div>
                  ) : repairCasesError ? (
                    <p className="px-2 py-3 text-xs text-red-300">
                      {repairCasesError}
                    </p>
                  ) : repairCasesByStatus
                      .length === 0 ? (

                    <div>
                      <p className="px-2 py-3 text-xs text-slate-500">
                        No repair cases
                      </p>


                      <Link
                        to="/repair-cases"
                        className="block rounded-lg px-2 py-2 text-xs font-semibold text-primary-100 transition-colors hover:bg-slate-800 hover:text-white"
                      >
                        View all repair cases
                      </Link>

                    </div>

                  ) : (

                    <ul className="space-y-1">


                      {/*
                       * iterate over status groups
                       */}
                      {repairCasesByStatus.map(
                        ({
                          status,
                          cases,
                        }) => {

                          // determine whether group is open
                          const statusOpen =
                            openStatus ===status


                          return (

                            <li key={status}>
                              <button
                                type="button"

                                onClick={() =>
                                  toggleStatus(
                                    status,
                                  )
                                }

                                className="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-sm text-slate-300 transition-colors hover:bg-slate-800 hover:text-white"
                              >

                                {statusOpen ? (
                                  <ChevronDown className="h-4 w-4 shrink-0" />
                                ) : (
                                  <ChevronRight className="h-4 w-4 shrink-0" />
                                )}

                                <span className="flex-1 text-left">
                                  {formatStatus(
                                    status,
                                  )}
                                </span>
                                <span className="rounded-full bg-slate-700 px-2 py-0.5 text-xs text-white">
                                  {cases.length}
                                </span>

                              </button>
                              {statusOpen && (

                                <ul className="ml-4 space-y-1 py-1">


                                  {/*
                                   * create link for every repair case
                                   */}
                                  {cases.map(
                                    (
                                      repairCase,
                                    ) => (

                                      <li
                                        key={
                                          repairCase
                                            .repairCaseId
                                        }
                                      >
                                        {/*
                                         *dynamic route
                                         */}
                                        <Link
                                          to={`/repair-cases/${repairCase.repairCaseId}`}

                                          className="flex items-center gap-2 rounded-lg px-2 py-2 text-xs text-slate-400 transition-colors hover:bg-slate-800 hover:text-white"
                                        >
                                          <Circle className="h-2 w-2 shrink-0 fill-current" />
                                          <span className="truncate">
                                            {
                                              repairCase
                                                .title
                                            }
                                          </span>
                                        </Link>
                                      </li>
                                    ),
                                  )}
                                </ul>
                              )}
                            </li>
                          )
                        },
                      )}
                      <li className="pt-2">
                        <Link
                          to="/repair-cases"
                          className="block rounded-lg px-2 py-2 text-xs font-semibold text-primary-100 transition-colors hover:bg-slate-800 hover:text-white">
                          View all repair cases
                        </Link>

                      </li>

                    </ul>
                  )}
                </div>
              )}
            </li>
            <li>
              <NavLink
                to="/team"
                className={navLinkStyle}
              >
                <Users
                  className={iconStyle}
                />

                <span>
                  Team
                </span>
              </NavLink>
            </li>
            <li>
              <NavLink
                to="/console-models"
                className={navLinkStyle}
              >
                <Boxes
                  className={iconStyle}
                />

                <span>
                  Console Models
                </span>
              </NavLink>
            </li>

          </ul>


          {/*
           * main diagnostic action
           */}
          <div className="mt-6 border-t border-slate-700 pt-6">

            <Link
              to="/component-tests/new"
              className="flex text-sm items-center justify-center gap-3 rounded-lg bg-emerald-500 px-4 py-3 font-semibold text-white shadow-sm transition-all hover:bg-emerald-600 hover:shadow-md active:scale-[0.98]"
            >
              <FlaskConical className="h-5 w-5 shrink-0" />

              <span>
                Run Component Test
              </span>
            </Link>

          </div>

        </div>

      </nav>

    </aside>
  )
}


// convert enum to user friendly text
const formatStatus = (status) => {

  return status
    .replaceAll('_', ' ')
    .toLowerCase()
    .replace(
      /\b\w/g,
      (character) =>
        character.toUpperCase(),
    )
}


export default Sidebar