import axios from 'axios'

import {
  clearAuthentication,
  getAccessToken,
} from '../auth/authStorage'

// creates a reusable axios client for every request to the backend, if VITE_API_URL exists, use that value. Otherwise, connect to local backend

const apiClient = axios.create({
  baseURL:
    import.meta.env.VITE_API_URL ??
    'http://localhost:8080/api/v1',

  // accept JSON responses

  headers: {
    Accept: 'application/json',
  },

  // cancel if there is no response in 30 secons
  timeout: 30000,
})

// request interceptor. this funcion runs before every http request, gets tge JWT from localStorage and adds it to the Authorization header

apiClient.interceptors.request.use(
  (config) => {
    const token = getAccessToken()

    if (token) {
      config.headers.Authorization =
        `Bearer ${token}`
    }

    // when the body is FormData, generate Content-Type + multipart

    if (config.data instanceof FormData) {
      delete config.headers['Content-Type']
    }

    return config
  },

  // reject promise if there is an error
  (error) => Promise.reject(error),
)

// response interceptor

apiClient.interceptors.response.use(
  (response) => response,

  (error) => {
    // error response does not exist when the backend did not return any HTTP response

    if (!error.response) {
      error.userMessage =
        error.code === 'ECONNABORTED'
          ? 'The request took too long to complete.'
          : 'Could not connect to the RetroLab backend.'

      return Promise.reject(error)
    }

    const status = error.response.status
    const responseData =
      error.response.data

    // 401 -> Sprin Security rejected authentication, token is removed

    if (status === 401) {
      clearAuthentication()

      // let React know that the authentication is no longer valid --> back to the login page

      window.dispatchEvent(
        new Event('authentication-expired'),
      )
    }

    // MethodArgumentNotValidException can return various messages

    if (
      Array.isArray(
        responseData?.errors,
      ) &&
      responseData.errors.length > 0
    ) {
      error.userMessage =
        responseData.errors.join(' ')
    } else if (
      typeof responseData === 'string'
    ) {
      // support endpoints that return error as plain text

      error.userMessage = responseData
    } else if (responseData?.message) {
      // ApiError responses generated by the GlobalExceptionHandler, placeholders if theres no message

      error.userMessage =
        responseData.message
    } else if (status === 401) {
      error.userMessage =
        'Your session has expired. Please log in again.'
    } else if (status === 403) {
      error.userMessage =
        'You do not have permission to perform this action.'
    } else if (status === 404) {
      error.userMessage =
        'The requested resource was not found.'
    } else if (status === 409) {
      error.userMessage =
        'The request conflicts with existing data.'
    } else if (status >= 500) {
      error.userMessage =
        'An unexpected backend error occurred.'
    } else {
      error.userMessage =
        `Request failed with status ${status}.`
    }

    // keep the original AxiosError instead of a normal one

    return Promise.reject(error)
  },
)

export default apiClient